### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jalandoak** [jacopom/kindleToRoam#1]
Hello,

I'm not much of a programmer, but I did try to fix this. I'm getting the following error:

`Traceback (most recent call last):
  File "kindleToRoam.py", line 16, in <module>
    lines[line].rsplit('(',1)[1][:-2]
IndexError: list index out of range
`

I know it's not much to go on, so if you tell me what you need, I'll get it for you.

**Comment by jacopom** [comment]
Hi Alan, thanks for signaling, it looks it is related to the extraction of author names.
Would it be possible for me to look at the "My Clippings.txt" files you are using? you can send a copy to martolinij [at] gmail.com

**Comment by jalandoak** [comment]
Added authors to those titles without, and it worked great! Thanks!
